# Generated by Django 4.2.7 on 2023-11-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_mymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legs", models.IntegerField()),
            ],
            options={
                "db_table": "Pets",
            },
        ),
        migrations.RenameModel(
            old_name="Mymodel",
            new_name="My_model",
        ),
    ]
