# Generated by Django 4.2.7 on 2023-11-08 05:20

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_student_alter_animal_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, db_column="Date_Time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="student",
            name="School",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="test",
            name="name",
            field=models.CharField(
                help_text="Test to check if this works.",
                max_length=20,
                validators=[home.models.end_with],
            ),
        ),
    ]
