# Generated by Django 4.2.7 on 2023-11-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_author_publisher_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="headshot",
        ),
    ]
