# Generated by Django 4.2.7 on 2023-11-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_hospital_name_remove_hospital_nurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='nurse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.nurse'),
        ),
    ]
